### ISSUE TITLE
Automatic Crashing on player connecting

### ISSUE THREAD

**Issue by sogr404** [CritteRo/FiveDivision#3]
There seems to be an issue with login register script that crashes the server whenever a player connects, I have tried to fix it myself, but I have had no luck, is there something I am missing?

**CritteRo's edit:**
Crash issue fixed by updating server artifacts.

**Comment by CritteRo** [comment]
That's weird... do you have any errors in server or client console? or in phpMyAdmin?

**Comment by sogr404** [comment]
No, I could try reinstalling the database, which Ill do rn, but it just automatically crashes the server side

**Comment by CritteRo** [comment]
Can you share a screenshot of the server console? Before anyone joins the server?

**Comment by sogr404** [comment]
![image](https://user-images.githubusercontent.com/82279776/135332981-662e2e31-5740-41e2-af94-44b53fbb59a5.png)

**Comment by sogr404** [comment]
Just reinstalled the database, still the same issue

**Comment by CritteRo** [comment]
You are missing core resources. mapmanager, spawnmanager and sessionmanager are all required.

This is what you should have:
```markdown
#Default resources: NEEDED
ensure mapmanager
ensure chat
ensure spawnmanager
ensure sessionmanager
ensure hardcap
#ensure rconlog
ensure baseevents
ensure playernames

#Custom resources:
ensure pma-voice
ensure oxmysql
#ensure critLobby #optional.
ensure critScaleforms
ensure scalePhone
ensure critPlayerlist
ensure XNLRankBar
ensure load-all-map
ensure warmenu
ensure hbw
ensure blip_info 

ensure divCore
ensure divOutposts
```
You can find all the other resources, either in my github, or on the cfx forum.

**Comment by sogr404** [comment]
After doing all of this, issue is still occuring

**Comment by CritteRo** [comment]
Do you have any other errors in server console? Are you running the server on your local computer? Are you running the server on a linux or windows machine?

**Comment by sogr404** [comment]
Im running it on a localhost rn, on windows, there are no other errors

**Comment by CritteRo** [comment]
can you update your server artifacts, and then send me another screenshot of your console? also a screenshot of your client console, after you try to join the server.

**Comment by sogr404** [comment]
"also...are you running other scripts too? other than what I sent you?" No

After updating the artifacts it seems to be working, but I get stuck on awaiting scripts

**Comment by CritteRo** [comment]
"but I get stuck on awaiting scripts" If you get stuck on Awaiting scripts, that means the spawnmanager, sessionmanager or divCore is not running correctly.

You should have an error in client console (F8)

**Comment by sogr404** [comment]
Yeah, seems Im going to have to reinstall the core, I shouldn't need any help from me, tysm

**Comment by CritteRo** [comment]
Ok great. Keep in mind that the gamemode doesn't have much at the moment, because it's finished *at all*.
After the account is created (first server join), make sure to go into the database > users, and set your "admin" value to 4.

"/getAllCosmetics" command should give you all available clothing items.
"/createcharacter" command starts the character creation menu.
"/wardrobe" is where you can select your clothes and hair style, and "/variations" is where you change the clothes textures / colors.
"/weapons" is the weapons menu. You can give yourself more weapons with "/addweapon [weaponname, without "weapon_"]" and weapon mods with "/addwmod [weaponmod] [weaponname, without "weapon_"]"

If you have any questions, send me a DM on the cfx forum: https://forum.cfx.re/u/critter/summary
